apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pre-prod-pipeline
  # Identify the Product Team Namespace within the PaaS
  namespace: vapo-demo
  annotations:
    app.kubernetes.io/managed-by: helm
spec:
  params:
    - name: pathToDockerFile
      type: string
      description: The path to the dockerfile to build
      default: $(resources.inputs.git-project-resource.path)/build/2201-vic-dev
  resources:
    # Identify required Git Resource for Pipeline
    - name: source-code
      type: git
      optional: false
    # Identify the destination for the Image Registry
    - name: vapo-image-registry
      type: image
      optional: false
  # Identify the Pipeline Tasks for Application Onboarding
  tasks:
    # Compiling the Code
    - name: unit-testing
      params:
      taskRef: 
        name: 1-unit-test-code-coverage
      resources:
        inputs:
        - name: source
          resource: source-code
    # Building the Image
    - name: sast-scanning
      runAfter: 
        - unit-testing
      taskRef:
        name: 2-sast
    - name: compile-to-nexus
      runAfter: 
        - sast-scanning
      testRef:
        name: 3-compile-and-send-2-nexus
    - name: build-image-scan-with-oci
      # This is used to help setup the series of events in the appropriate order
      runAfter: 
        - compile-to-nexus
      taskRef:
        name: 4-buildah-task
      params:
        - name: pathToDockerFile
          value: /build/2201-vic-dev
      resources:
        inputs:
        - name: source
          resource: vic-source
        outputs:
        - name: image-destination
          resource: vapo-image-registry
    - name: send-cve-report
      runAfter:
        - build-image-scan-with-oci
      taskRef:
        name: 5-cve-trivy-scanner
      params:
        - name: scan-image
          value: quay.io/ksummersill2/trivy:0.17.1
      resources:
        inputs:
        - name: image-to-scan
          resource: vapo-image-registry
    - name: end-to-end-testing
      runAfter:
        - send-cve-report
      taskRef:
        name: 6-end-to-end-testing
    - name: dast-scanning
      runAfter:
        - end-to-end-testing
      taskRef: 
        name: 7-dast-scanning
    - name: deploy-stack
      runAfter:
        - dast-scanning
      taskRef:
        name: 8-helm-app-deployer

        