apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: source-code
  namespace: vapo-demo
  annotations:
    app.kubernetes.io/managed-by: helm
spec:
  type: git
  params:
  - name: url
    value: https://github.com/department-of-veterans-affairs/vapo-vic.git
  - name: revision
    value: vapo