apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: vapo-image-registry
  namespace: vapo-demo
  annotations:
    app.kubernetes.io/managed-by: helm
spec:
  type: image
  params:
  - name: url
    value: quay.vapo.va.gov/vic-dev/dev:1.0.0