apiVersion: apps/v1
kind: Deployment
metadata:
  name: vic-frontend
  namespace: vapo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vic-frontend
  template: 
    metadata:
      labels:
        app: vic-frontend
    spec:
      containers:
      - name: vic-frontend
        image: quay.vapo.va.gov/vic-dev/dev:1.0.0
        ports:
        - name: https
          containerPort: 2424
          protocol: TCP
      imagePullSecrets:
      - name: vapo-quay
