apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: helm-pipeline-deployer
  namespace: vapo-demo
spec:
  serviceAccountName: pipeline
  params:
  - name: HELM_IMAGE
    value: "quay.vapo.va.gov/vapo_tst_images/helm-oc-rocky:1.0.0"
  - name: VAPO_PIPELINE_REPO
    value: "https://appddictionstudio.github.io/chart-releaser-test/"
  - name: HELM_CHART_NAME
    value: "maven-tomcat-deployment"
  - name: HELM_CHART_VERSION
    value: "1.0.0"
  - name: HELM_NAMESPACE
    value: "vapo-demo"
  - name: HELM_VERSION
    value: "1.0.0"
  taskRef:
    name: helm-pipeline-deployer-task