apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vapo
  name: get-pods
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelines"]
  verbs: ["get", "list", "create"]
- apiGroups: ["tekton.dev"]
  resources: ["tasks"]
  verbs: ["get", "list", "create"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineresources"]
  verbs: ["get", "list", "create"]