apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: nmap
spec:
  inputs: 
    params:
    - name: targetIP
      type: string
      description: host IP we are targeting
      default: "127.0.0.1"
  steps:
  - name: nmap-test
    image: quay.io/ksummersill2/ubuntu-wget:1.0.0
    script: |
      mkdir -p /nmap/home/
      echo "Install nmap"
      apt-get install sudo
      apt-get install nmap -y
      nmap $(inputs.params.targetIP) && \
      sudo nmap $(inputs.params.targetIP) -O && \
      nmap $(inputs.params.targetIP) -sT && \
      nmap $(inputs.params.targetIP) -p http,https && \
      nmap $(inputs.params.targetIP) -sL && \
      nmap $(inputs.params.targetIP) -sV && \
      sudo nmap $(inputs.params.targetIP) -f -oX /nmap/home/dast-report.xml
      cat /nmap/home/dast-report.xml
      curl -v -u admin:4ca9c9e3-a593-4832-ba6a-f5c5336d1853 --upload-file
        /nmap/home/dast-report.xml
        http://nexus3-openshift-operators.apps.vapo-ppd.va.gov/repository/vic/1.0/pentest/dast-report.xml

        echo "DAST report Upload Complete
        
### below is the taskrun ref for nmap with parameters#### 
#      - name: dast-scanning
#       params:
#       -name: targetIP
#        value: http://servicename.namespace.svc.cluster.local
#       taskRef: 
#         name: 7-dast-scanning-nmap
#       runAfter:
#         - end-to-end-testing

