apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: owasp-zap
spec:
  workspaces:
    - name: local-maven-repo
      description: |
        The folder where the output of the script run is saved
      mountPath: /zap/wrk
  inputs: 
    params:
    - name: site
      type: string
      description: Site we are targeting
      default: "site url"
    - name: strength
      type: string
      description: Attack strength, default is MEDIUM, it can be Low, Medium, High or Insane
      default: "-config scanner.strength=MEDIUM -config scanner.threshold=MEDIUM"
    - name: path
      type: string
      description: Path of the pvc
      default: "/zap/wrk/"
  steps:
  - name: zap-test
    image: quay.io/vapo/owasp-zap:v1.0.0
    script: |
      zap-full-scan.py -t $(inputs.params.site) -r $(inputs.params.path)testreport.html -d -z "$(inputs.params.strength)"
      cat /zap/wrk/testreport.html
    - image: 'quay.io/ksummersill2/ubuntu-wget:1.0.1'
      name: nexus-3-zap-scan-report
      resources: {}
      script: >
        curl -v -u admin:4ca9c9e3-a593-4832-ba6a-f5c5336d1853 --upload-file
        /zap/wrk/testreport.html
        http://nexus3-openshift-operators.apps.vapo-ppd.va.gov/repository/vic/1.0/cve-scans/testreport.html

        echo "nmap report Upload Complete"
       
      ### below is the taskrun ref for owazp with parameters#### 
#      - name: dast-scanning
#       params:
#       -name: site
#        value: http://servicename.namespace.svc.cluster.local
#       taskRef: 
#         name: 7-dast-scanning-owasp-zap
#       runAfter:
#         - end-to-end-testing
