apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: 8-deployment
  namespace: vapo-demo
  annotations:
    app.kubernetes.io/managed-by: helm
spec:
  steps:
    - name: deploying-stack
      image: quay.io/ksummersill2/ubuntu-wget:1.0.0
      script: |
        echo "Deploying the Application"
