Pipeline:
  Namespace: vic-2201-demo

PipelineResource:
  mainSourceCode: https://github.com/department-of-veterans-affairs/vapo-vic.git
  mainBranch: vapo
  imageRepositoryLocation: quay.vapo.va.gov/vic-dev/dev:1.0.0
