apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: 5-cve-trivy-scanner
  namespace: {{ .Values.Pipeline.Namespace }}
  annotations:
    app.kubernetes.io/managed-by: helm
spec:
  inputs:
    params:
    - name: scan-image
      description: the trivy command used within the trivy container.
      type: string
      default: quay.io/ksummersill2/trivy:0.17.2
    resources:
    - name: image-source
      type: image
  steps:
    - name: get-latest-cve-findings
      image: quay.io/ksummersill2/ubuntu-wget:1.0.0
      script: |
        mkdir -p /tekton/home/.cache/trivy/db
        wget -O /tekton/home/.cache/trivy/db/trivy-offline.db.tgz https://github.com/aquasecurity/trivy-db/releases/latest/download/trivy-offline.db.tgz --no-check-certificate
        cd /tekton/home/.cache/trivy/db
        tar xvf trivy-offline.db.tgz
    - name: trivy-scanner
      image: $(inputs.params.scan-image)
      script: |
        trivy image --clear-cache 
        trivy image --skip-update --severity='HIGH,CRITICAL' --vuln-type='os,library' --format='table' $(inputs.resources.image-source.url) > /tekton/home/cve-report.txt
        cat /tekton/home/cve-report.txt
    - name: nexus-3-cve-report-upload
      image: quay.io/ksummersill2/ubuntu-wget:1.0.1
      script: |
        curl -v -u admin:4ca9c9e3-a593-4832-ba6a-f5c5336d1853 --upload-file /tekton/home/cve-report.txt http://nexus3-openshift-operators.apps.vapo-ppd.va.gov/repository/vic/1.0/cve-scans/cve-report.txt
        echo "CVE Upload Complete"
  volumes:
    - name: trivy-db
      emptyDir: {}