apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: 7-dast-scanning-owasp-zap
  namespace: {{ .Values.Pipeline.Namespace }}
spec:
  params:
    - default: '80'
      description: Sets the runtime port used for OWASP
      name: RUNTIME_PORT
      type: string
    - default: '-config scanner.strength=MEDIUM -config scanner.threshold=MEDIUM'
      description: Identify the OWASP Pen. testing strategy strength. 
      name: OWASP_STRENGTH
      type: string
    - default: projectx
      description: Identify the project name for NEXUS3
      name: NEXUS3_PROJECT_NAME
      type: string
  sidecars:
    - image: 'quay.vapo.va.gov/vapo-training/vapo-trng:1.0.0'
      name: deploy-image
      resources: {}
  steps:
    - image: 'quay.io/vapo/owasp-zap:v1.0.0'
      name: run-owasp-zap-test
      resources: {}
      script: >
        curl http://localhost:$(params.RUNTIME_PORT)

        zap-full-scan.py -t http://localhost:$(params.RUNTIME_PORT) > results.txt

        curl -v -u admin:#Newyear2065# --upload-file results.txt
        http://nexus3-openshift-operators.apps.vapo-ppd.va.gov/repository/vapo/$(params.NEXUS3_PROJECT_NAME)/results.txt
