apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: 7-dast-scanning-owasp-zap
  namespace: {{ .Values.Pipeline.Namespace }}
spec:
  params:
    - default: site url
      description: Site we are targeting
      name: site
      type: string
    - default: '-config scanner.strength=MEDIUM -config scanner.threshold=MEDIUM'
      description: >-
        Attack strength, default is MEDIUM, it can be Low, Medium, High or
        Insane
      name: strength
      type: string
    - default: /zap/wrk/
      description: Path of the pvc
      name: path
      type: string
  sidecars:
    - image: 'quay.vapo.va.gov/vapo-training/vapo-trng:1.0.0'
      name: deploy-image
      resources: {}
  steps:
    - image: 'quay.io/vapo/owasp-zap:v1.0.0'
      name: run-owasp-zap-test
      resources: {}
      script: >
        curl http://localhost:2424

        zap-full-scan.py -t http://localhost:2424 > results.txt

        curl -v -u admin:#Newyear2065# --upload-file results.txt
        http://nexus3-openshift-operators.apps.vapo-ppd.va.gov/repository/vapo/projectx/results.txt
