apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: helm-app-deployer
  namespace: {{ .Values.Pipeline.Namespace }}
  annotations:
    app.kubernetes.io/managed-by: helm
spec:
  inputs:
    params:
    - name: HELM_IMAGE
      type: "string"
      default: "quay.vapo.va.gov/vapo_tst_images/helm-oc-rocky:1.0.0"
    - name: VAPO_PIPELINE_REPO
      type: "string"
      default: "https://department-of-veterans-affairs.github.io/vapo-pipelines/"
    - name: HELM_CHART_NAME
      type: "string"
      default: "maven-tomcat-deployment"
    - name: HELM_CHART_VERSION
      type: "string"
      default: "1.0.0"
    - name: HELM_NAMESPACE
      type: "string"
      default: "vapo-demo"
    - name: HELM_VERSION
      type: "string"
      default: "1.0.0"
  steps:
  - name: deploy-pipeline
    image: $(params.HELM_IMAGE)
    script: |
      helm version
      helm upgrade $(params.HELM_VERSION) $(params.HELM_CHART_NAME) --install --namespace $(params.HELM_NAMESPACE) --version $(params.HELM_CHART_VERSION) --repo $(params.VAPO_PIPELINE_REPO)
