apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: 8-deployment
  namespace: {{ .Values.Pipeline.Namespace }}
  annotations:
    app.kubernetes.io/managed-by: helm
spec:
  inputs:
    params:
    - name: working-directory
      type: string
      default: "/workspace/source"
      description: Identifies the location of the source code within the workspace
    - name: oc-deployment-template
      type: string
      default: $(params.working-directory)/build/2201-vic-dev-template
      description: The file name for the deployment template
    - name: project-name
      type: string
      default: {{ .Values.Pipeline.Namespace }}
      description: Name of project
    - name: app-name
      type: string
      default: vic
      description: Name of App. 
    - name: branch-name
      type: string
      default: vapo
      description: Identifes the name of the branch
    - name: git-url
      type: string
      default: https://github.com/department-of-veterans-affairs/vapo-vic.git
      description: Identifies the url path of the git repo. 
  steps:
    - name: deploying-stack
      image: quay.vapo.va.gov/vapo_tst_images/helm-oc-rocky:1.0.0
      script: |
        oc version
        oc apply -f /workspace/source/build/2201-vic-dev-template
