kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: vic-route
  namespace: vapo-demo
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    openshift.io/host.generated: 'true'
spec:
  to:
    kind: Service
    name: vic-service
    weight: 100
  port:
    targetPort: 2424
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None