apiVersion: v1
kind: Secret
metadata:
  name: vic-dev-vicdevdeployrobot-pull-secret
  namespace: vapo-demo
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LnZhcG8udmEuZ292IjogewogICAgICAiYXV0aCI6ICJkbWxqTFdSbGRpdDJhV05rWlhaa1pYQnNiM2x5YjJKdmREcEhWbGRFUjFSRlUxWktPVEZHUjA5QlJFZERVRXRhUTFwT1ZURTFVa2RDVmtGU1VqVXhURFEwTms4eE5rSlhTVXhKVlV0Uk0weFBUVFJDV1VaUVZrYzUiLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson